config/routes.rb
Rails.application.routes.draw do

  get '/db_backup', to: 'static_pages#db_backup'

  get 'wishes', to: 'wishes#unfulfilled', as: 'wishes', format: :html

  root 'sessions#new'
  get 'auth/facebook/callback', to: 'sessions#facebook'

  get 'error/:error_id', to: 'htmlerrors#error_status_page'

  get    '/login',   to: 'sessions#new', as: 'login'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  get '/help',             to: 'static_pages#help'
  #get '/home',             to: 'static_pages#home'

  get 'my_recipient',       to: 'friends#recipient',  as: 'recipient'
  get 'my_generation',      to: 'generations#my_gen'
  get 'user',               to: 'friends#user',       as: 'user'

  get 'gifts/giver/:giver_id/recipient/:recipient_id', to: 'gifts#from_to', as: 'from_to'

  get 'friend_wishes_ajax/:id', to: 'wishes#friend_wishes_ajax'

  get 'new_message_to_recipient', to: 'friend_messages#new_message_to_recipient'
  get 'new_message_to_giver',     to: 'friend_messages#new_message_to_giver'
  get 'messages_as_giver',        to: 'friend_messages#messages_as_giver'
  get 'messages_as_recipient',    to: 'friend_messages#messages_as_recipient'
  get 'unread_messages',          to: 'friend_messages#unread'

  resources :friend_messages, only: [:show, :index], format: :html

  resources :generations, only: [:show, :index], format: :html

  resources :gifts, format: :html

  get 'wishes/all',    to: 'wishes#all', as: 'all_wishes'



  # the index method for the wishes controller shows only unfulfilled wishes
  # the all method shows all wishes
  # the same applies for friends/:friend_id/wishes/[index/all]

  resources :friends, only: [:show, :index], format: :html do
    member do
      get 'generation',         to: "friends#generation"
      get 'giving_gifts',       to: 'friends#giving'
      get 'receiving_gifts',    to: 'friends#receiving'
      get 'wishes/unfulfilled', to: 'wishes#friend_unfulfilled'
      get 'wishes/all',         to: 'wishes#friend_all', as: 'all_wishes'
      get 'wishes',             to: 'wishes#friend_unfulfilled', as: 'wishes'
    end
    resources :gifts,   only: [:index, :new], format: :html
    # '/friends/gifts/index' will list the gifts that a friend is receiving
  end

  resources :wishes, except: [:index], format: :html do
    resources :gifts, only: [:index, :new], format: :html
  end

  get   'amazon/import',        to: 'amazon#import'
  post  'amazon/import',        to: 'amazon#create_list'
  get   'amazon/show_list/:id', to: 'amazon#show_list'

  get 'privacy_policy',         to: 'static_pages#privacy_policy'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/friend.rb
class Friend < ApplicationRecord

  has_many :giver_matches, foreign_key: :giver_id, class_name: 'FriendMatch'
  has_many :recipient_matches, foreign_key: :recipient_id, class_name: 'FriendMatch'
  has_many :recipients, through: :giver_matches, source: :giver
  has_many :givers, through: :recipient_matches, source: :recipient

  has_many  :received_gifts, foreign_key: :recipient_id, class_name: 'Gift'
  has_many  :given_gifts, foreign_key: :giver_id, class_name: 'Gift'
  has_many  :wishes

  has_many  :received_messages, foreign_key: :recipient_id, class_name: "FriendMessage"
  has_many  :sent_messages, foreign_key: :sender_id, class_name: 'FriendMessage'

  belongs_to  :generation

  has_many  :amazon_wishes
  has_many  :amazon_lists

  has_many  :facebooks, dependent: :destroy

  has_secure_password

  def Friend.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def messages
    received_messages + sent_messages
  end

  def unread_messages
    messages.reject(&:read?)
  end

  def forbidden_matches
    ForbiddenMatch.where("friend_1_id = ? OR friend_2_id = ?", self.id, self.id)
  end

  def giver_match # the match from this year in which this friend is the giver
    giver_matches.find {|gm| gm.year == Time.christmas_year}
  end

  def recipient_match # the match from this year in which this friend is the
    recipient_matches.find {|rm| rm.year == Time.christmas_year} # => recipient
  end

  def giver # the person that this friend is giving too this year
    recipient_match.giver if giver_match
  end

  def recipient # the person that this friend is recieving from this year
    giver_match.recipient if giver_match
  end

  def gifts_from(other_friend)
    Gift.where(recipient: self, giver: other_friend)
  end

  def forbidden_match?(other_friend)
    return true if other_friend == self
    ForbiddenMatch.where(
      friend_1: [self, other_friend], friend_2: [self, other_friend]
    ).exists?
  end

  def self.without_wishes
    naughty_list = Friend.all.to_a.reject do |f|
      Wish.where(year: Time.christmas_year, friend_id: f.id).any?
    end
    naughty_list
  end

end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController

  def show
    @friend = Friend.find(params[:id])
    @friends = Friend.all
    @wishes = Wish.where(year: Time.christmas_year, friend_id: @friend.id).to_a
    @gifts = Gift.where(year: Time.christmas_year).select do |gift|
      gift.recipient_id != current_user.id
      @wishes.any? { |wish| wish.id == gift.wish_id }
    end
  end

  def index
    @friends = Friend.all
    @generations = Generation.all
    @gifts = Gift.where(year: Time.christmas_year).to_a.reject do |gift|
      gift.recipient_id == current_user.id
    end
  end

  def recipient
    @friend = current_user.recipient
    @friends = Friend.all
    @wishes = Wish.where(year: Time.christmas_year, friend_id: @friend.id).to_a
    @gifts = Gift.where(year: Time.christmas_year).to_a.reject do |gift|
      gift.recipient_id != current_user.id
      @wishes.any? { |wish| wish.id == gift.wish_id }
    end
    render 'show' and return
  end

  def user
    @friend = current_user
    @friends = Friend.all
    @wishes = Wish.where(year: Time.christmas_year, friend_id: @friend.id).to_a + []
    @gifts = Gift.where(year: Time.christmas_year).select do |gift|
      gift.recipient_id != current_user.id
      @wishes.any? { |wish| wish.id == gift.wish_id }
    end
    render 'show' and return
  end

  def generation
    @generation = Generation.find_by(id: params[:id])
    if @generation
      redirect_to @generation
    else
      render status: 404, file: "#{Rails.root}/public/404.html" and return
    end
  end

  def giving
    if params[:id]
      @giver = Friend.find_by(id: params[:id])
      @gifts = Gift.where(year: Time.christmas_year, giver_id: params[:id]).to_a.reject do |gift|
        gift.recipient_id == current_user.id
      end
      render 'gifts/index'
    else
      render status: 404, file: "#{Rails.root}/public/404.html" and return
    end
  end

  def receiving
    if params[:id].to_i == current_user.id
      render status: 403, file: "#{Rails.root}/public/403.html" and return
    elsif params[:id]
      @gifts = Gift.where(year: Time.christmas_year, recipient_id: params[:id])
      render 'gifts/index'
    else
      render status: 404, file: "#{Rails.root}/public/403.html" and return
    end
  end

end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/views/friends/_radio_buttons.html.erb
<% raise unless f %>

<% if params[:friend_id] %>
  <%= f.hidden_field(:recipient_id, value: params[:friend_id]) %>
<% elsif params[:wish_id] %>
  <%= f.hidden_field(:recipient_id, value: Wish.find(params[:wish_id]).friend_id) %>
<% else %>
  <%= f.label :recipient_id, 'Who is this gift for?' %>
  <%= f.select(:recipient_id, Friend.all.to_a.map{ |fr| [fr.name, fr.id]}.prepend(["", nil]),
    id: 'gift_recipient_select') %>
<% end %>

<% if params[:wish_id] %>
  <%= f.hidden_field :wish_id, value: params[:wish_id] %>
<% elsif params[:friend_id] %>
  <%= f.collection_select(:wish_id, Friend.find(params[:friend_id]).wishes, :id,
  :title, include_blank: true, id: 'gift_wish_select') %>
<% else %>
  <%= f.label :wish_id, "What wish, if any, is this gift fulfilling?" %>
  <%= f.select :wish_id, [], include_blank: true, id: 'gift_wish_select' %>
<% end %>

<script type="text/javascript">
var $url_arr = window.location.href.split("/");
var $root_url = $url_arr[0] + "//" + $url_arr[2];
$("select#gift_recipient_id").change(function(){
  var full_url = $root_url + "/friend_wishes_ajax" + "/" + $("select#gift_recipient_id option:selected:first").val() + ".json";
  $('select#gift_wish_id option:gt(0)').remove();
  $.getJSON( full_url, function( data ) {
    $.each( data, function( ind, val ) {
      $("select#gift_wish_id").append($("<option></option>")
        .attr("value", val["id"]).text(val["title"]));
    });
  });
});
</script>

app/views/friends/index.html.erb
<% provide(:title, "Friends") %>

<% @generations.all.each do |gen| %>
  <%= render partial: "generations/generation_friends.html.erb", locals: {gen: gen} %>
<% end %>

app/views/friends/show.html.erb
<% provide(:title, @friend.name) %>

<h1><%= @friend.name %></h1>

<% if current_user.recipient == @friend %>
  <h3>This person is your recipient</h3>
  <%= link_to 'Send them a message', 'new_message_to_recipient' %>
<% end %>

<br>
<% if @friend == current_user %>
  <%= link_to "Add gift to wishlist", new_wish_path %>
<% else %>
  <%= link_to "#{@friend.name}'s wishlist", wishes_friend_path(@friend) %><br>
  <%= link_to "Give this person a gift", new_friend_gift_path(@friend) %>
<% end %>

<% unless @friend == current_user %>
  <h2><%= link_to "All gifts that #{@friend.name} is receiving", receiving_gifts_friend_path(@friend) %></h2>
<% end %>

<br>
<h2>Generation</h2>
<%= link_to @friend.generation.name, generation_friend_path(@friend) %>