config/routes.rb
Rails.application.routes.draw do

  get '/db_backup', to: 'static_pages#db_backup'

  get 'wishes', to: 'wishes#unfulfilled', as: 'wishes', format: :html

  root 'sessions#new'
  get 'auth/facebook/callback', to: 'sessions#facebook'

  get 'error/:error_id', to: 'htmlerrors#error_status_page'

  get    '/login',   to: 'sessions#new', as: 'login'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  get '/help',             to: 'static_pages#help'
  #get '/home',             to: 'static_pages#home'

  get 'my_recipient',       to: 'friends#recipient',  as: 'recipient'
  get 'my_generation',      to: 'generations#my_gen'
  get 'user',               to: 'friends#user',       as: 'user'

  get 'gifts/giver/:giver_id/recipient/:recipient_id', to: 'gifts#from_to', as: 'from_to'

  get 'friend_wishes_ajax/:id', to: 'wishes#friend_wishes_ajax'

  get 'new_message_to_recipient', to: 'friend_messages#new_message_to_recipient'
  get 'new_message_to_giver',     to: 'friend_messages#new_message_to_giver'
  get 'messages_as_giver',        to: 'friend_messages#messages_as_giver'
  get 'messages_as_recipient',    to: 'friend_messages#messages_as_recipient'
  get 'unread_messages',          to: 'friend_messages#unread'

  resources :friend_messages, only: [:show, :index], format: :html

  resources :generations, only: [:show, :index], format: :html

  resources :gifts, format: :html

  get 'wishes/all',    to: 'wishes#all', as: 'all_wishes'



  # the index method for the wishes controller shows only unfulfilled wishes
  # the all method shows all wishes
  # the same applies for friends/:friend_id/wishes/[index/all]

  resources :friends, only: [:show, :index], format: :html do
    member do
      get 'generation',         to: "friends#generation"
      get 'giving_gifts',       to: 'friends#giving'
      get 'receiving_gifts',    to: 'friends#receiving'
      get 'wishes/unfulfilled', to: 'wishes#friend_unfulfilled'
      get 'wishes/all',         to: 'wishes#friend_all', as: 'all_wishes'
      get 'wishes',             to: 'wishes#friend_unfulfilled', as: 'wishes'
    end
    resources :gifts,   only: [:index, :new], format: :html
    # '/friends/gifts/index' will list the gifts that a friend is receiving
  end

  resources :wishes, except: [:index], format: :html do
    resources :gifts, only: [:index, :new], format: :html
  end

  get   'amazon/import',        to: 'amazon#import'
  post  'amazon/import',        to: 'amazon#create_list'
  get   'amazon/show_list/:id', to: 'amazon#show_list'

  get 'privacy_policy',         to: 'static_pages#privacy_policy'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/friend_message.rb
class FriendMessage < ApplicationRecord
  belongs_to :sender, foreign_key: 'sender_id', class_name: 'Friend'
  belongs_to :recipient, foreign_key: 'recipient_id', class_name: 'Friend'
  belongs_to :friend_match

  before_validation :set_year, on: [:create, :save]

  def match_giver
    friend_match.giver
  end

  def match_recipient
    friend_match.recipient
  end

  def sender_name(current_user)
    if sender == current_user
      'you'
    elsif sender == current_user.giver
      "your giver"
    elsif sender == current_user.recipient
      "your recipient #{current_user.recipient.name}"
    else
      'do not read'
    end
  end

  def recipient_name(current_user)
    if recipient == current_user
      'you'
    elsif recipient == current_user.giver
      "your giver"
    elsif recipient == current_user.recipient
      "your recipient #{current_user.recipient.name}"
    else
      'do not read'
    end
  end

  private

  def set_year
    self.year = Time.christmas_year
  end

end

app/controllers/friend_messages_controller.rb
class FriendMessagesController < ApplicationController
  before_action :set_friend_message, only: [:show, :edit, :update, :destroy]

  # GET /friend_messages
  # GET /friend_messages.json
  def index
    @friend_messages = current_user.messages.to_a.sort_by(&:created_at).reverse
    @index_type = nil
    mark_messages_as_read(@friend_messages)
  end

  def messages_as_giver
    @friend_messages = current_user.giver_match.messages.to_a
    @friend_messages.to_a.sort_by!(&:created_at).reverse!
    @index_type = :as_giver
    @giver = 'you'
    @recipient = "your recipient #{current_user.recipient.name}"
    render 'index'
    mark_messages_as_read(@friend_messages)
  end

  def messages_as_recipient # NOT the same thing as recieved messages!
    @friend_messages = current_user.recipient_match.messages.to_a
    @friend_messages.sort_by!(&:created_at).reverse!
    @index_type = :as_recipient
    render 'index'
    @giver = 'your giver'
    @recipient = 'you'
    mark_messages_as_read(@friend_messages)
  end

  def unread
    @friend_messages = FriendMessage.where(recipient_id: current_user.id, read?: false).to_a
    @friend_messages.sort_by!(&:created_at).reverse!
    @index_type = :unread
    mark_messages_as_read(@friend_messages)
  end

  # GET /friend_messages/1
  # GET /friend_messages/1.json
  def show
    @friend_message = FriendMessage.find_by(id: params[:id])
    unless [@friend_message.sender_id, @friend_message.recipient_id].include?(current_user.id)
      render status: 403, file: "#{Rails.root}/public/403.html" and return
    end
  end

  # GET /friend_messages/new
  def new_message_to_recipient
    @sending_to = :recipient
    @friend_message = FriendMessage.new(sender_id: current_user.id,
      recipient_id: current_user.recipient.id,
      friend_match_id: current_user.giver_match.id)
    render 'new'
  end

  def new_message_to_giver
    @sending_to = :giver
    @friend_message = FriendMessage.new(sender_id: current_user.id,
      recipient_id: current_user.giver.id,
      friend_match_id: current_user.recipient_match.id)
    render 'new'
  end

  # POST /friend_messages
  # POST /friend_messages.json
  def create
    @friend_message = FriendMessage.new(friend_message_params)
    respond_to do |format|
      if @friend_message.save
        format.html do
          FriendMailer.fm_notification(@friend_message)
          redirect_to @friend_message, notice: 'Friend message was successfully created.'
        end
        format.json do
          FriendMailer.fm_notification(@friend_message)
          render :show, status: :created, location: @friend_message
        end
      else
        format.html { render :new }
        format.json { render json: @friend_message.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend_message
      @friend_message = FriendMessage.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def friend_message_params
      params.require(:friend_message).permit(:friend_match_id, :sender_id, :recipient_id, :content)
    end

    def mark_messages_as_read(messages)
      messages.each { |m| m.update_attribute(:read?, true) }
    end
end

app/helpers/friend_messages_helper.rb
module FriendMessagesHelper
end

app/views/friend_messages/_form.html.erb
<%= form_with(model: friend_message, local: true) do |form| %>
  <% if friend_message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(friend_message.errors.count, "error") %> prohibited this friend_message from being saved:</h2>

      <ul>
      <% friend_message.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.hidden_field :friend_match_id,
    value: (@sending_to == :recipient ? current_user.giver_match.id : current_user.recipient_match.id) %>
  <%= form.hidden_field :sender_id, value: current_user.id %>
  <%= form.hidden_field :recipient_id, value: @friend_message.recipient_id %>
  <%= form.hidden_field :friend_match_id, value: @friend_message.friend_match_id %>

  <div class="field">
    <%= form.label :content, "Your message" %>
    <%= form.text_area :content, id: :friend_message_content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/friend_messages/index.html.erb
<p id="notice"><%= notice %></p>

<p>
  <% if @index_type == :as_giver %>
    <h1><%= "Messages between you and your recipient #{current_user.recipient.name}" %></h1>
    <%= link_to "Messages between you and your giver", messages_as_recipient_path %><br>
    <%= link_to 'All messages', friend_messages_path %><br>
  <% elsif @index_type == :as_recipient %>
    <h1><%= "Messages between you and your giver" %></h1>
    <%= link_to "Messages between you and your recpient #{current_user.recipient.name}", messages_as_giver_path %><br>
    <%= link_to 'All messages', friend_messages_path %><br>
  <% elsif @index_type == :unread %>
    <h1><%= "Unread messages" %></h1>
    <%= link_to "Messages between you and your giver", messages_as_recipient_path %><br>
    <%= link_to "Messages between you and your recpient #{current_user.recipient.name}", messages_as_giver_path %><br>
    <%= link_to 'All messages', friend_messages_path %><br>
  <% else %>
    <h1>All Messages</h1>
    <%= link_to "Messages between you and your recipient #{current_user.recipient.name}", messages_as_recipient_path %><br>
    <%= link_to 'Messages between you and your giver', messages_as_giver_path %><br>
  <% end %>
</p>

<table border="5">
  <thead>
    <tr>
      <th colspan="2">Sender</th>
      <th colspan="2">Recipient</th>
      <th colspan="5">Content</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @friend_messages.each do |friend_message| %>
      <tr>
        <td colspan="2"><%= friend_message.sender_name(current_user) %></td>
        <td colspan="2"><%= friend_message.recipient_name(current_user) %></td>
        <td colspan="5"><%= friend_message.content %></td>
        <td colspan="2"><%= link_to 'View/reply', friend_message %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New message to your giver', 'new_message_to_giver' %><br>
<%= link_to "New message to your recipient #{current_user.recipient.name}", 'new_message_to_recipient' %><br>

app/views/friend_messages/new.html.erb
<% if @friend_message.match_giver == current_user %>
  <h1>New message to your giver</h1>
  <%= image_tag 'boy_whispering_to_anon.png' %>
<% else %>
  <h1>New message to your recipient</h1>
  <%= image_tag 'anon_whispering_to_girl.png' %>
  <h2> Remember not to tell them who you are!!!!!</h2>
<% end %>

<%= render 'form', friend_message: @friend_message %>

<%= link_to 'Back', friend_messages_path %>

<% if @friend_message.match_giver == current_user %>
  <% link_to 'send a message to your recipient instead' 'new_message_to_recipient' %>
  <%= image_tag '/images/anon_whispering_to_girl.png' %>
<% else %>
  <% link_to 'send a message to your giver instead' 'new_message_to_giver' %>
  <%= image_tag '/images/boy_whispering_to_anon.png' %>
<% end %>

app/views/friend_messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <% if @friend_message.sender == current_user && @friend_message.recipient == current_user.giver %>
    <h1>A message from you to your giver</h1>
    <%= image_tag 'boy_whispering_to_anon.png' %>
  <% elsif @friend_message.sender == current_user && @friend_message.recipient == current_user.recipient %>
    <h1><%= "A message from you to your recipient #{current_user.recipient.name}" %></h1>
    <%= image_tag 'anon_whispering_to_girl.png' %>
  <% elsif @friend_message.recipient == current_user.recipient %>
    <h1><%= "A message from your recipient #{current_user.recipient.name} to you" %></h1>
    <%= image_tag 'boy_whispering_to_anon.png' %>
  <% else %>
    <h1>A message from your giver to you</h1>
    <%= image_tag 'anon_whispering_to_girl.png' %>
  <% end %>
</p>

<p>
  <strong>Content:</strong>
  <%= @friend_message.content %>
</p>

<%= link_to 'Reply', (@friend_message.friend_match == current_user.giver_match ? 'new_message_to_recipient' : 'new_message_to_giver') %>

<%= link_to 'Back', friend_messages_path %>