config/routes.rb
Rails.application.routes.draw do

  get '/db_backup', to: 'static_pages#db_backup'

  get 'wishes', to: 'wishes#unfulfilled', as: 'wishes', format: :html

  root 'sessions#new'
  get 'auth/facebook/callback', to: 'sessions#facebook'

  get 'error/:error_id', to: 'htmlerrors#error_status_page'

  get    '/login',   to: 'sessions#new', as: 'login'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  get '/help',             to: 'static_pages#help'
  #get '/home',             to: 'static_pages#home'

  get 'my_recipient',       to: 'friends#recipient',  as: 'recipient'
  get 'my_generation',      to: 'generations#my_gen'
  get 'user',               to: 'friends#user',       as: 'user'

  get 'gifts/giver/:giver_id/recipient/:recipient_id', to: 'gifts#from_to', as: 'from_to'

  get 'friend_wishes_ajax/:id', to: 'wishes#friend_wishes_ajax'

  get 'new_message_to_recipient', to: 'friend_messages#new_message_to_recipient'
  get 'new_message_to_giver',     to: 'friend_messages#new_message_to_giver'
  get 'messages_as_giver',        to: 'friend_messages#messages_as_giver'
  get 'messages_as_recipient',    to: 'friend_messages#messages_as_recipient'
  get 'unread_messages',          to: 'friend_messages#unread'

  resources :friend_messages, only: [:show, :index], format: :html

  resources :generations, only: [:show, :index], format: :html

  resources :gifts, format: :html

  get 'wishes/all',    to: 'wishes#all', as: 'all_wishes'



  # the index method for the wishes controller shows only unfulfilled wishes
  # the all method shows all wishes
  # the same applies for friends/:friend_id/wishes/[index/all]

  resources :friends, only: [:show, :index], format: :html do
    member do
      get 'generation',         to: "friends#generation"
      get 'giving_gifts',       to: 'friends#giving'
      get 'receiving_gifts',    to: 'friends#receiving'
      get 'wishes/unfulfilled', to: 'wishes#friend_unfulfilled'
      get 'wishes/all',         to: 'wishes#friend_all', as: 'all_wishes'
      get 'wishes',             to: 'wishes#friend_unfulfilled', as: 'wishes'
    end
    resources :gifts,   only: [:index, :new], format: :html
    # '/friends/gifts/index' will list the gifts that a friend is receiving
  end

  resources :wishes, except: [:index], format: :html do
    resources :gifts, only: [:index, :new], format: :html
  end

  get   'amazon/import',        to: 'amazon#import'
  post  'amazon/import',        to: 'amazon#create_list'
  get   'amazon/show_list/:id', to: 'amazon#show_list'

  get 'privacy_policy',         to: 'static_pages#privacy_policy'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/gift.rb
class Gift < ApplicationRecord
  belongs_to  :wish, optional: true
  belongs_to  :giver, class_name: 'Friend'
  belongs_to  :recipient, class_name: 'Friend'
  validates_associated  :giver
  validates_associated  :recipient
  validate :valid_purchase_status
  before_validation :set_year, on: [:create, :save]

  def set_year
    self.year = Time.christmas_year
  end

  def valid_purchase_status
    unless ["purchased", "intend", 'sent'].include?(purchase_status)
      errors.add(:purchase_status, "can only be be 'purchased', 'intend', or 'sent'")
    end
  end
end

app/controllers/gifts_controller.rb
class GiftsController < ApplicationController

  def show
    @gift = Gift.find_by(id: params[:id])
    if @gift.nil?
      render status: 404, file: "#{Rails.root}/public/404.html" and return
    elsif @gift.recipient == @current_user # to do: make sure this works
      render status: 403, file: "#{Rails.root}/public/403.html" and return
      # to do: maybe have something other than an error here?
    end
  end

  def index
    if params[:friend_id].to_i == @current_user.id.to_i
      render status: 403, file: "#{Rails.root}/public/403.html" and return
      # to do: maybe have something other than an error here?
    elsif params[:friend_id]
      @friend = Friend.find_by(id: params[:friend_id])
      @wish = Wish.find_by(id: params[:wish_id])
      @receiving_gifts = Gift.where(recipient: @friend, year: Time.christmas_year).to_a.reject do |f|
        f.recipient_id == current_user.id
      end
      @giving_gifts = Gift.where(giver: @friend, year: Time.christmas_year).to_a.reject do |f|
        f.recipient_id == current_user.id
      end
      render 'friend_gifts' and return # to do: make this
    else
      @gifts = Gift.where(year: Time.christmas_year)
      render 'index' and return # to do: make this
    end
  end

  def new
    @gift = Gift.new
    @wish = Wish.find_by(id: params[:wish_id])
    @recipient = Friend.find_by(id: params[:friend_id])
    if @wish && @recipient && @wish.friend != @recipient
      render status: 404, file: "#{Rails.root}/public/404.html" and return
    end
    @giver = current_user
  end

  def create
    @gift = Gift.new(gift_params)
    if (@gift.recipient != current_user) && @gift.save
      flash[:success] = 'Gift saved'
      redirect_to Friend.find_by(id: @gift.recipient)
      # to do: customize this by the incoming url
    elsif @gift.recipient == current_user
      flash[:danger] = "You can't give a gift to yourself"
      render 'give'
      # to do: customize this by the incoming url
    else
      flash[:danger] = "Gift not saved"
      render 'give'
      # to do: customize this by the incoming url
    end
  end

  def edit
    @gift = Gift.find(params[:id])
    unless @gift.giver == current_user
      flash[:danger] = 'You can only edit gifts that you are giving'
      redirect_to(@gift)
      # to do: customize this by the incoming url
    end
  end

  def update
    @gift = Gift.find_by(id: params[:id])
    if @gift.update(gift_params)
      flash[:success] = "Gift updated"
      redirect_to(@gift)
      # to do: customize this by the incoming url
    else
      flash[:danger] = "Gift update not saved"
      render 'edit_wish' # to do: customize this by the incoming url
    end
  end

  def destroy
    begin
      @gift = Gift.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      render status: 404, file: "#{Rails.root}/public/404.html"
      return
    end
    if @gift.giver == current_user
     if @gift.destroy
       flash[:success] = "Gift deleted"
     else
       flash[:danger] = "Gift not deleted"
     end
   else
     flash[:danger] = "You may only delete gifts that you are giving"
   end
   redirect_to(current_user) # to do: customize this by the incoming url
  end

  def from_to
    if !(params[:giver_id] && params[:recipient_id])
      render status: 404, file: "#{Rails.root}/public/404.html" and return
    elsif params[:recipient_id].to_i == current_user.id.to_i
      render status: 403, file: "#{Rails.root}/public/403.html" and return
    else
      @giver = Friend.find_by(id: params[:giver_id])
      @recipient_id = Friend.find_by(id: params[:recipient_id])
      render 'index' and return
    end
  end

  private

    def gift_params
      params.require(:gift).permit(:title, :description, :wish_id, :year,
        :recipient_id, :purchase_status, :giver_id)
    end

end

app/helpers/gifts_helper.rb
module GiftsHelper
  
end

app/views/gifts/_gift.html.erb
<% raise unless current_user && gift %>
<% if gift.recipient == current_user %>
  <% raise %>
<% else %>
  <% gift_title = gift.title %>
  <% fulfillment_of = gift.wish ? gift.wish.name : 'none' %>
  <% description = gift.description %>
<% end %>

<ul>
  <% unless gift.recipient == current_user%>
    <li><%= link_to gift_title, gift %></li>
    <li>
      <% if gift.giver == gift.recipient.special_friend_giver %> /* to do: add this to the model */
        <% "#{gift.giver.name.capitalize}'s special friend" %>
      <% else %>
        Recipient: <%= link_to gift.recipient.name, gift.recipient %>
      <% end %>
    </li>
    <li>Description: <%= description %></li>
    <% if fulfillment_of %>
      <li>Fulfillment of: <%= fulfillment_of %></li> /* to do: makes sure this works */
    <% end %>
    <li>Shipped: <%= !!gift.shipped %></li>
    <li>Received: <%= @gift.received %>
      <% if gift.recipient == current_user.name %> <%# to do: reformat this */ %>
        <%= link_to "Give an update about whether this gift has arrived",
        edit_gift_path(gift.id) %>
      <% end %>
    </li>
  <% end %>
</ul>

app/views/gifts/_gift_selectors.html.erb
<% raise unless f %>

<% if params[:friend_id] %>
  <%= f.hidden_field(:recipient_id, value: params[:friend_id]) %>
<% elsif params[:wish_id] %>
  <%= f.hidden_field(:recipient_id, value: Wish.find(params[:wish_id]).friend_id) %>
<% else %>
  <%= f.label :recipient_id, 'Who is this gift for?' %>
  <%= f.select(:recipient_id, Friend.all.to_a.map{ |fr| [fr.name, fr.id]}.prepend(["", nil]),
    id: 'gift_recipient_select') %><br>
<% end %>

<% if params[:wish_id] %>
  <%= f.hidden_field :wish_id, value: params[:wish_id] %>
<% elsif params[:friend_id] %>
  <%= f.collection_select(:wish_id, Friend.find(params[:friend_id]).wishes, :id,
  :title, include_blank: true, id: 'gift_wish_select') %>
<% else %>
  <%= f.label :wish_id, "What wish, if any, is this gift fulfilling?" %>
  <%= f.select :wish_id, [], include_blank: true, id: 'gift_wish_select' %>
<% end %>

<script type="text/javascript">
var $url_arr = window.location.href.split("/");
var $root_url = $url_arr[0] + "//" + $url_arr[2];
$("select#gift_recipient_id").change(function(){
  var full_url = $root_url + "/friend_wishes_ajax" + "/" + $("select#gift_recipient_id option:selected:first").val() + ".json";
  $('select#gift_wish_id option:gt(0)').remove();
  $.getJSON( full_url, function( data ) {
    $.each( data, function( ind, val ) {
      $("select#gift_wish_id").append($("<option></option>")
        .attr("value", val["id"]).text(val["title"]));
    });
  });
});
</script>

app/views/gifts/_gifts_summary.html.erb
<% raise unless current_user && gifts %>
<TABLE BORDER="5">
  <tr>
    <th>Title</th>
    <% if @giver %>
      <th>Giver</th>
    <% end %>
    <% if @recipient %>
      <th>Recipient</th>
    <% end %>
    <% unless @wish %>
      <th>Fulfills wish</th>
    <% end %>
    <th>Purchase status</th>
  </tr>
  <% gifts.each do |gift| %>
    <% unless current_user == gift.recipient %>
      <tr>
        <td><%= link_to gift.title, gift %></td>
        <% if @giver %>
        <td><%= gift.giver.name %></td>
        <% end %>
        <% if @recipient %>
        <td><%= gift.recipient.name %></td>
        <% end %>
        <% unless @wish %>
        <td><%= (gift.wish.nil?) ? 'None' : gift.wish.title %></td>
        <% end %>
        <td><%= gift.purchase_status %></td>
      </tr>
    <% end %>
  <% end %>
</TABLE>

app/views/gifts/_list_gifts.html.erb
<ul>
  <% @gifts.each do |gift| %>
    <li>
      <ul>
      <% if (gift.giver == current_user) %>
      <li><%= link_to "Title: #{gift.title}", gift_path(id: gift.id) %></li>
      <li>Recipient: <%= link_to "#{gift.recipient}", friend_path(id:
      (@friends.find {|friend| friend.name == gift.name}).id) %></li>
      <li>Description: <%= gift.description %></li>
      <li>Fulfillment of: <%= gift ? gift.wish.name, 'none' %></li> /* to do: makes sure this works */
      <li>Shipped: <%= gift.shipped %></li>
      <% if @gift.received %>
        <li>Received: <%= @gift.received %></li>
      <% else %>
        <li>Not yet received</li>
      <% end %>

      <% elsif gift.recipient == current_user.name %>
        <li><%= link_to "?????????", gift_path(id: gift.id) %></li>
        <li>Recipient: <%= link_to "#{gift.recipient}", friend_path(id: (@friends.find {|friend| friend.name == gift.recipient.name}).id) %></li>
        <li>Giver: <%= link_to "#{gift.giver}", friend_path(id: (@friends.find {|friend| friend.name == gift.giver.name}).id) %></li>
        <li>Wished for?: <%= gift.asked_for %></li>
        <li>Shipped: <%= gift.shipped %></li>
        <% if !!@gift.received == true %>
          <li>Received on: <%= @gift.received %></li>
        <% else %>
          <li><%= link_to "Let people know you've received this!", received_path(id: gift.id)</li> %>
        <% end %>
      <% else %>
        <li><%= link_to "Title: #{gift.title}", gift_path(id: gift.id) %></li>
        <li>Recipient: <%= link_to "#{gift.recipient}", friend_path(id: (@friends.find {|friend| friend.name == gift.name}).id) %></li>
        <li>Giver: <%= link_to "#{gift.giver}", friend_path(id: (@friends.find {|friend| friend.name == gift.giver.name}).id) %></li>
      <% end %>
      </ul>
    </li>
  <% end %>
</ul>

app/views/gifts/edit.html.erb
<% provide(:title, 'New gift') %>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@gift) do |f| %>

      <%= f.label :title, " Title" %>
      <%= f.text_field :title, class: 'form-control' %><br>

      <%= f.label :description, "A longer description of your gift with any relevant details, including URLs, ISBNs, etc" %>
      <%= f.text_area :description, :cols => "10", :rows => "10", class: 'form-control' %><br>


      <%= f.label :recipient_id, 'Who is this gift for?' %>
      <%= f.collection_select(:recipient_id, Friend.all, :id, :name,
        include_blank: false, id: 'gift_recipient_select', selected: @gift.recipient.id) %>

      <%= f.label :wish_id, "What wish, if any, is this gift fulfilling?" %>
      <%= f.collection_select(:wish_id, @gift.recipient.wishes, :id,
        :title, include_blank: true, id: 'gift_wish_select',
        selected: (@gift.wish ? @gift.wish.id : nil)) %>

      <h4>Have you purcased and/or sent this gift yet?</h4>
      <%= f.label :purchase_status_intend, "I have not yet purchased this item, but I intend to" %>
      <%= f.radio_button :purchase_status, "intend", checked: true %>
      <%= f.label :purchase_status_purchased, "I have already purchased this item, but have not sent it out yet" %>
      <%= f.radio_button :purchase_status, "purchased" %>
      <%= f.label :purchase_status_sent, "I have already purchased and sent this item" %>
      <%= f.radio_button :purchase_status, "sent" %><br>

      <%= f.hidden_field :giver_id, value: current_user.id %>
      <%= f.hidden_field :year, value: Time.christmas_year %>

      <%= f.submit "Give gift", class: "btn btn-primary" %>
      <%= link_to "Cancel", friend_path(id: current_user.id) %>
    <% end %>
  </div>
  <script type="text/javascript">
  var $url_arr = window.location.href.split("/");
  var $root_url = $url_arr[0] + "//" + $url_arr[2];
  $("select#gift_recipient_id").change(function(){
    var full_url = $root_url + "/friend_wishes_ajax" + "/" + $("select#gift_recipient_id option:selected:first").val() + ".json";
    $('select#gift_wish_id option:gt(0)').remove();
    $.getJSON( full_url, function( data ) {
      $.each( data, function( ind, val ) {
        $("select#gift_wish_id").append($("<option></option>")
          .attr("value", val["id"]).text(val["title"]));
      });
    });
  });
  </script>
</div>

app/views/gifts/friend_gifts.html.erb
<% provide(:title, "#{@friend.name}'s Gifts") %>

<%# to do: improve this %>
<h1>Gifts that <%= @friend.name %> is giving</h1>
<%= render partial: 'gifts_summary', locals: {gifts: @giving_gifts, giver: nil, recipient: nil} %>

<br>

<h1>Gifts that <%= @friend.name %> is receiving</h1>
<%= render partial: 'gifts_summary', locals: {gifts: @receiving_gifts, giver: nil, recipient: nil} %>

<br>

<%= link_to "Give #{@friend.name} a gift", new_friend_gift_path(@friend) %>

app/views/gifts/index.htm.erb
<% provide(:title, "Gifts") %>

<ul>
  <% @gifts.each do |gift| %>
    <li>
      <% if (gift.giver == logged_in_user) %>
        <li><%= link_to "Title: #{gift.title}", gift_path(id: gift.id) %></li>
        <li>Recipient: <%= link_to "#{gift.recipient}", friend_path(id: (@friends.find {|friend| friend.name == gift.name}).id) %></li>
        <li>Description: <%= gift.description %></li>
        <li>Wished for?: <%= gift.asked_for %></li>
        <li>Fulfilled?: <%= gift.intend_to_give %></li>
        <li>Shipped: <%= gift.shipped %></li>
        <% if !!@gift.recieved == true %>
          <li>Recieved on: <%= @gift.recieved %></li>
        <% else %>
          <li>Not yet recieved</li>
        <% end %>
      <% elsif gift.recipient == logged_in_user.name %>
        <li><%= link_to "?????????", gift_path(id: gift.id) %></li>
        <li>Recipient: <%= link_to "#{gift.recipient}", friend_path(id: (@friends.find {|friend| friend.name == gift.recipient.name}).id) %></li>
        <li>Giver: <%= link_to "#{gift.giver}", friend_path(id: (@friends.find {|friend| friend.name == gift.giver.name}).id) %></li>
        <li>Wished for?: <%= gift.asked_for %></li>
        <li>Shipped: <%= gift.shipped %></li>
        <% if !!@gift.recieved == true %>
          <li>Recieved on: <%= @gift.recieved %></li>
        <% else %>
          <li><%= link_to "Let people know you've recieved this!", recieved_path(id: gift.id)</li> %>
        <% end %>
      <% else %>
        <li><%= link_to "Title: #{gift.title}", gift_path(id: gift.id) %></li>
        <li>Recipient: <%= link_to "#{gift.recipient}", friend_path(id: (@friends.find {|friend| friend.name == gift.name}).id) %></li>
        <li>Giver: <%= link_to "#{gift.giver}", friend_path(id: (@friends.find {|friend| friend.name == gift.giver.name}).id) %></li>
      <% end %>
    </li>
  <% end %>
</ul>

app/views/gifts/index.html.erb
<% controller.redirect_to '/error/403' if @recipient == current_user %>
<br>
<%= link_to "Enter a new gift", new_gift_path %>
<br>
<h1>Gifts</h1>
<%# to do: improve this %>
<%= render partial: 'gifts/gifts_summary', locals: {gifts: @gifts, wish: @wish,
  recipient: @recipient, giver: @giver
} %>

app/views/gifts/new.html.erb
<% provide(:title, 'New gift') %>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@gift) do |f| %>

      <%= f.label :title, "Title" %>
      <%= f.text_field :title, class: 'form-control'  %><br>

      <%= f.label :description, "A longer description of your gift with any relevant details, including URLs, ISBNs, etc" %>
      <%= f.text_area :description, :cols => "10", :rows => "10", class: 'form-control'  %><br>

      <% if @recipient %>
        <%= f.hidden_field :recipient_id, value: @recipient.id %>
        <%= f.label :wish_id, "What wish, if any, is this wish fulfilling?" %>
        <%= f.collection_select(:wish_id, Friend.find(@recipient.id).wishes, :id,
        :title, include_blank: true, id: 'gift_wish_select') %>
      <% else %>
        <%= render partial: "gift_selectors.html.erb", locals: {f: f, params: params}, object: @wish%>
      <% end %><br>

      <h4>Have you purcased and/or sent this gift yet?</h4>
      <%= f.label :purchase_status_intend,
        "I have not yet purchased this item, but I intend to" %>
      <%= f.radio_button :purchase_status, "intend",
        checked: @gift.purchase_status == 'intend' %>
      <%= f.label :purchase_status_purchased,
        "I have already purchased this item, but have not sent it out yet" %>
      <%= f.radio_button :purchase_status, "purchased",
        checked: @gift.purchase_status == 'purchased' %>
      <%= f.label :purchase_status_sent,
        "I have already purchased and sent this item" %>
      <%= f.radio_button :purchase_status, "sent",
        checked: @gift.purchase_status == 'sent' %>

      <%= f.hidden_field :giver_id, value: current_user.id %>
      <%= f.hidden_field :year, value: Time.christmas_year %>

      <%= f.submit "Give gift", class: "btn btn-primary" %>
      <%= link_to "Cancel", friend_path(id: current_user.id) %>
    <% end %>
  </div>
</div>

app/views/gifts/request.html.erb
<% provide(:title, 'Request gift') %>
<h1>Add gift to wishlist</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@gift) do |f| %>
      <%= f.label :title, "A brief title for your wish" %>
      <%= f.text_field :title %>

      <%= f.label :description, "A longer description of your wish with any relevant details, including URLs, ISBN, etc" %>
      <%= f.text_area :description, :cols => "10", :rows => "10" %>

      <% :asked_for = true %>
      <% :recipient = logged_in_user.name %>
      <% :intend_to_give = false %>
      <% :recieved = nil %>
      <% :giver = nil %>
      <% :shipped = nil %>
      <% :shipping_details = nil %>


      <%= f.submit "Make wish", class: "btn btn-primary" %>
      <%= link_to "Cancel", friend_path(id: logged_in_user.id) %>
    <% end %>
  </div>
</div>

app/views/gifts/show.html.erb
<% provide(:title, @gift.title) unless current_user == @gift.recipient %>

<% if current_user == @gift.recipient %>
  <h1>Stop trying to peek at your presents</h1>
<% else %>
  <h1><%= @gift.title %></h1>
  <h4>Description</h4>
  <%= @gift.description %>
  <h4>Recipient</h4>
  <%= @gift.recipient.name %>
  <% if @gift.wish %>
    <h4>Fulfillment of wish:</h4>
    <%= link_to @gift.wish.title, wish_path(@gift.wish) %>
  <% end %>
  <h4>Purchase Status</h4>
  <%= @gift.purchase_status %>
<% end %>

<% if (current_user == @gift.giver) %>
  <br>
  <%= link_to "Edit", edit_gift_path(@gift) %>
  <br>
  <%= link_to "Delete", gift_path(@gift), method: :delete, data: { confirm:
    'Are you sure you want to delete this?' } %>
<% end %>