config/routes.rb
Rails.application.routes.draw do

  get '/db_backup', to: 'static_pages#db_backup'

  get 'wishes', to: 'wishes#unfulfilled', as: 'wishes', format: :html

  root 'sessions#new'
  get 'auth/facebook/callback', to: 'sessions#facebook'

  get 'error/:error_id', to: 'htmlerrors#error_status_page'

  get    '/login',   to: 'sessions#new', as: 'login'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  get '/help',             to: 'static_pages#help'
  #get '/home',             to: 'static_pages#home'

  get 'my_recipient',       to: 'friends#recipient',  as: 'recipient'
  get 'my_generation',      to: 'generations#my_gen'
  get 'user',               to: 'friends#user',       as: 'user'

  get 'gifts/giver/:giver_id/recipient/:recipient_id', to: 'gifts#from_to', as: 'from_to'

  get 'friend_wishes_ajax/:id', to: 'wishes#friend_wishes_ajax'

  get 'new_message_to_recipient', to: 'friend_messages#new_message_to_recipient'
  get 'new_message_to_giver',     to: 'friend_messages#new_message_to_giver'
  get 'messages_as_giver',        to: 'friend_messages#messages_as_giver'
  get 'messages_as_recipient',    to: 'friend_messages#messages_as_recipient'
  get 'unread_messages',          to: 'friend_messages#unread'

  resources :friend_messages, only: [:show, :index], format: :html

  resources :generations, only: [:show, :index], format: :html

  resources :gifts, format: :html

  get 'wishes/all',    to: 'wishes#all', as: 'all_wishes'



  # the index method for the wishes controller shows only unfulfilled wishes
  # the all method shows all wishes
  # the same applies for friends/:friend_id/wishes/[index/all]

  resources :friends, only: [:show, :index], format: :html do
    member do
      get 'generation',         to: "friends#generation"
      get 'giving_gifts',       to: 'friends#giving'
      get 'receiving_gifts',    to: 'friends#receiving'
      get 'wishes/unfulfilled', to: 'wishes#friend_unfulfilled'
      get 'wishes/all',         to: 'wishes#friend_all', as: 'all_wishes'
      get 'wishes',             to: 'wishes#friend_unfulfilled', as: 'wishes'
    end
    resources :gifts,   only: [:index, :new], format: :html
    # '/friends/gifts/index' will list the gifts that a friend is receiving
  end

  resources :wishes, except: [:index], format: :html do
    resources :gifts, only: [:index, :new], format: :html
  end

  get   'amazon/import',        to: 'amazon#import'
  post  'amazon/import',        to: 'amazon#create_list'
  get   'amazon/show_list/:id', to: 'amazon#show_list'

  get 'privacy_policy',         to: 'static_pages#privacy_policy'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SpecialFriends</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <% if current_user %>
      <header class = "navbar navbar-fixed-top navbar-inverse">
        <div class="container">
          <%= link_to 'Special Friends', '#', id: 'logo' %>
          <nav>
            <ul class="nav navbar-nav navbar-right">
              <li><%= link_to "Messages (#{FriendMessage.where(recipient_id: current_user.id, read: false).count} unread)", friend_messages_path %></li>
              <li><%= link_to "All Friends", friends_path %></li>
              <li><%= link_to "All Unfulfilled Wishes", wishes_path %></li>
              <li><%= (link_to "My Recipient (#{current_user.recipient.name})", recipient_path) if current_user.recipient %></li>
              <li><%= link_to "Me (#{current_user.name})", user_path %></li>
              <li><%= link_to "My Wish List", all_wishes_friend_path(current_user) %></li>
              <li><%= link_to "Make A Wish", '/wishes/new' %></li>
              <li><%= link_to "Gift's I'm Giving", giving_gifts_friend_path(current_user) %></li>
              <li><%= link_to "Logout", logout_path, method: :delete %></li>
              <li><%= link_to "Help", '/help' %></li>
              <li><%= link_to "Import Amazon Wishlist", '/amazon/import' %></li>
              <li><%= link_to 'Link Facebook profile', '/auth/Facebook' unless current_user.facebooks.any? %></li>
              <li><%= link_to 'Privacy policy', '/privacy_policy' %></li>
            </ul>
          </nav>
        </div>
      </header>
    <% end %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>